const country_list = {
        
  "AED": "ae",
  "AFN": "af",
  "ALL": "al",
  "AMD": "am",
  "ANG": "nl",
  "AOA": "ao",
  "ARS": "ar",
  "AUD": "au",
  "AWG": "aw",
  "AZN": "az",
  "BAM": "ba",
  "BBD": "bb",
  "BDT": "bd",
  "BGN": "bg",
  "BHD": "bh",
  "BIF": "bi",
  "BMD": "bm",
  "BND": "bn",
  "BOB": "bo",
  "BRL": "br",
  "BSD": "bs",
  "BTN": "bt",
  "BWP": "bw",
  "BYN": "by",
  "BZD": "bz",
  "CAD": "ca",
  "CDF": "cd",
  "CHF": "ch",
  "CLP": "cl",
  "CNY": "cn",
  "COP": "co",
  "CRC": "cr",
  "CUP": "cu",
  "CVE": "cv",
  "CZK": "cz",
  "DJF": "dj",
  "DKK": "dk",
  "DOP": "do",
  "DZD": "dz",
  "EGP": "eg",
  "ERN": "er",
  "ETB": "et",
  "EUR": "eu",
  "FJD": "fj",
  "FKP": "fk",
  "FOK": "fo",
  "GBP": "gb",
  "GEL": "ge",
  "GGP": "gg",
  "GHS": "gh",
  "GIP": "gi",
  "GMD": "gm",
  "GNF": "gn",
  "GTQ": "gt",
  "GYD": "gy",
  "HKD": "hk",
  "HNL": "hn",
  "HRK": "hr",
  "HTG": "ht",
  "HUF": "hu",
  "IDR": "id",
  "ILS": "il",
  "IMP": "im",
  "INR": "in",
  "IQD": "iq",
  "IRR": "ir",
  "ISK": "is",
  "JEP": "je",
  "JMD": "jm",
  "JOD": "jo",
  "JPY": "jp",
  "KES": "ke",
  "KGS": "kg",
  "KHR": "kh",
  "KID": "ki",
  "KMF": "km",
  "KRW": "kr",
  "KWD": "kw",
  "KYD": "ky",
  "KZT": "kz",
  "LAK": "la",
  "LBP": "lb",
  "LKR": "lk",
  "LRD": "lr",
  "LSL": "ls",
  "LTL": "lt",
  "LVL": "lv",
  "LYD": "ly",
  "MAD": "ma",
  "MDL": "md",
  "MGA": "mg",
  "MKD": "mk",
  "MMK": "mm",
  "MNT": "mn",
  "MOP": "mo",
  "MRO": "mr",
  "MRU": "mr",
  "MUR": "mu",
  "MVR": "mv",
  "MWK": "mw",
  "MXN": "mx",
  "MYR": "my",
  "MZN": "mz",
  "NAD": "na",
  "NGN": "ng",
  "NIO": "ni",
  "NOK": "no",
  "NPR": "np",
  "NZD": "nz",
  "OMR": "om",
  "PAB": "pa",
  "PEN": "pe",
  "PGK": "pg",
  "PHP": "ph",
  "PKR": "pk",
  "PLN": "pl",
  "PYG": "py",
  "QAR": "qa",
  "RON": "ro",
  "RSD": "rs",
  "RUB": "ru",
  "RWF": "rw",
  "SAR": "sa",
  "SBD": "sb",
  "SCR": "sc",
  "SDG": "sd",
  "SEK": "se",
  "SGD": "sg",
  "SHP": "sh",
  "SLL": "sl",
  "SOS": "so",
  "SRD": "sr",
  "SSP": "ss",
  "STN": "st",
  "SYP": "sy",
  "SZL": "sz",
  "THB": "th",
  "TJS": "tj",
  "TMT": "tm",
  "TND": "tn",
  "TOP": "to",
  "TRY": "tr",
  "TTD": "tt",
  "TVD": "tv",
  "TZS": "tz",
  "UAH": "ua",
  "UGX": "ug",
  "USD": "us",
  "UYU": "uy",
  "UZS": "uz",
  "VES": "ve",
  "VND": "vn",
  "VUV": "vu",
  "WST": "ws",
  "XAF": "cf", 
  "XCD": "lc", 
  "XOF": "ci",
  "XPF": "pf",
  "YER": "ye",
  "ZAR": "za",
  "ZMW": "zm",
  "ZWL": "zw"
};


        // Define the currencies object for display names
        const currencies = {
            "AED": "UAE Dirham",
            "AFN": "Afghan Afghani",
            "ALL": "Albanian Lek",
            "AMD": "Armenian Dram",
            "ANG": "Netherlands Antillian Guilder",
            "AOA": "Angolan Kwanza",
            "ARS": "Argentine Peso",
            "AUD": "Australian Dollar",
            "AWG": "Aruban Florin",
            "AZN": "Azerbaijani Manat",
            "BAM": "Bosnia and Herzegovina Mark",
            "BBD": "Barbados Dollar",
            "BDT": "Bangladeshi Taka",
            "BGN": "Bulgarian Lev",
            "BHD": "Bahraini Dinar",
            "BIF": "Burundian Franc",
            "BMD": "Bermudian Dollar",
            "BND": "Brunei Dollar",
            "BOB": "Bolivian Boliviano",
            "BRL": "Brazilian Real",
            "BSD": "Bahamian Dollar",
            "BTN": "Bhutanese Ngultrum",
            "BWP": "Botswana Pula",
            "BYN": "Belarusian Ruble",
            "BZD": "Belize Dollar",
            "CAD": "Canadian Dollar",
            "CDF": "Congolese Franc",
            "CHF": "Swiss Franc",
            "CLP": "Chilean Peso",
            "CNY": "Chinese Renminbi",
            "COP": "Colombian Peso",
            "CRC": "Costa Rican Colon",
            "CUP": "Cuban Peso",
            "CVE": "Cape Verdean Escudo",
            "CZK": "Czech Koruna",
            "DJF": "Djiboutian Franc",
            "DKK": "Danish Krone",
            "DOP": "Dominican Peso",
            "DZD": "Algerian Dinar",
            "EGP": "Egyptian Pound",
            "ERN": "Eritrean Nakfa",
            "ETB": "Ethiopian Birr",
            "EUR": "Euro",
            "FJD": "Fiji Dollar",
            "FKP": "Falkland Islands Pound",
            "FOK": "Faroese Króna",
            "GBP": "Pound Sterling",
            "GEL": "Georgian Lari",
            "GGP": "Guernsey Pound",
            "GHS": "Ghanaian Cedi",
            "GIP": "Gibraltar Pound",
            "GMD": "Gambian Dalasi",
            "GNF": "Guinean Franc",
            "GTQ": "Guatemalan Quetzal",
            "GYD": "Guyanese Dollar",
            "HKD": "Hong Kong Dollar",
            "HNL": "Honduran Lempira",
            "HRK": "Croatian Kuna",
            "HTG": "Haitian Gourde",
            "HUF": "Hungarian Forint",
            "IDR": "Indonesian Rupiah",
            "ILS": "Israeli New Shekel",
            "IMP": "Manx Pound",
            "INR": "Indian Rupee",
            "IQD": "Iraqi Dinar",
            "IRR": "Iranian Rial",
            "ISK": "Icelandic Króna",
            "JEP": "Jersey Pound",
            "JMD": "Jamaican Dollar",
            "JOD": "Jordanian Dinar",
            "JPY": "Japanese Yen",
            "KES": "Kenyan Shilling",
            "KGS": "Kyrgyzstani Som",
            "KHR": "Cambodian Riel",
            "KID": "Kiribati Dollar",
            "KMF": "Comorian Franc",
            "KRW": "South Korean Won",
            "KWD": "Kuwaiti Dinar",
            "KYD": "Cayman Islands Dollar",
            "KZT": "Kazakhstani Tenge",
            "LAK": "Lao Kip",
            "LBP": "Lebanese Pound",
            "LKR": "Sri Lanka Rupee",
            "LRD": "Liberian Dollar",
            "LSL": "Lesotho Loti",
            "LTL": "Lithuanian Litas",
            "LVL": "Latvian Lats",
            "LYD": "Libyan Dinar",
            "MAD": "Moroccan Dirham",
            "MDL": "Moldovan Leu",
            "MGA": "Malagasy Ariary",
            "MKD": "Macedonian Denar",
            "MMK": "Myanmar Kyat",
            "MNT": "Mongolian Tugrik",
            "MOP": "Macanese Pataca",
            "MRO": "Mauritanian Ouguiya",
            "MRU": "Mauritanian Ouguiya",
            "MUR": "Mauritian Rupee",
            "MVR": "Maldivian Rufiyaa",
            "MWK": "Malawian Kwacha",
            "MXN": "Mexican Peso",
            "MYR": "Malaysian Ringgit",
            "MZN": "Mozambican Metical",
            "NAD": "Namibian Dollar",
            "NGN": "Nigerian Naira",
            "NIO": "Nicaraguan Córdoba",
            "NOK": "Norwegian Krone",
            "NPR": "Nepalese Rupee",
            "NZD": "New Zealand Dollar",
            "OMR": "Omani Rial",
            "PAB": "Panamanian Balboa",
            "PEN": "Peruvian Nuevo Sol",
            "PGK": "Papua New Guinean Kina",
            "PHP": "Philippine Peso",
            "PKR": "Pakistani Rupee",
            "PLN": "Polish Zloty",
            "PYG": "Paraguayan Guarani",
            "QAR": "Qatari Rial",
            "RON": "Romanian Leu",
            "RSD": "Serbian Dinar",
            "RUB": "Russian Ruble",
            "RWF": "Rwandan Franc",
            "SAR": "Saudi Riyal",
            "SBD": "Solomon Islands Dollar",
            "SCR": "Seychellois Rupee",
            "SDG": "Sudanese Pound",
            "SEK": "Swedish Krona",
            "SGD": "Singapore Dollar",
            "SHP": "Saint Helena Pound",
            "SLL": "Sierra Leonean Leone",
            "SOS": "Somali Shilling",
            "SRD": "Surinamese Dollar",
            "SSP": "South Sudanese Pound",
            "STN": "São Tomé and Príncipe Dobra",
            "SYP": "Syrian Pound",
            "SZL": "Eswatini Lilangeni",
            "THB": "Thai Baht",
            "TJS": "Tajikistani Somoni",
            "TMT": "Turkmenistani Manat",
            "TND": "Tunisian Dinar",
            "TOP": "Tongan Paʻanga",
            "TRY": "Turkish Lira",
            "TTD": "Trinidad and Tobago Dollar",
            "TVD": "Tuvaluan Dollar",
            "TZS": "Tanzanian Shilling",
            "UAH": "Ukrainian Hryvnia",
            "UGX": "Ugandan Shilling",
            "USD": "United States Dollar",
            "UYU": "Uruguayan Peso",
            "UZS": "Uzbekistani So'm",
            "VES": "Venezuelan Bolívar",
            "VND": "Vietnamese Đồng",
            "VUV": "Vanuatu Vatu",
            "WST": "Samoan Tala",
            "XAF": "Central African CFA Franc",
            "XCD": "East Caribbean Dollar",
            "XOF": "West African CFA Franc",
            "XPF": "CFP Franc",
            "YER": "Yemeni Rial",
            "ZAR": "South African Rand",
            "ZMW": "Zambian Kwacha",
            "ZWL": "Zimbabwean Dollar"
        };


        $(document).ready(function() {
    // Populate the select options dynamically
    let options = '';
    for (let code in currencies) {
        let flagUrl = `https://flagcdn.com/48x36/${country_list[code]}.png`;
        options += `<option value="${code}" data-img-src="${flagUrl}">${currencies[code]}</option>`;
    }

    // Make sure Select2 is initialized after options are loaded
    $('#from-currency, #to-currency').html(options).select2({
        templateResult: formatCurrencyOption,
        templateSelection: formatCurrencyOption,
        // Add state.id to search results
        matcher: function(params, data) {
            // If no search term, return all options
            if ($.trim(params.term) === '') {
                return data;
            }

            // Compare both the currency name and the state.id (currency code)
            if (data.text.toLowerCase().includes(params.term.toLowerCase()) || 
                data.id.toLowerCase().includes(params.term.toLowerCase())) {
                return data;
            }

            return null; // If no match, return null
        }
    });
});

// Modify formatCurrencyOption to show the currency code (state.id) as well
function formatCurrencyOption(state) {
    if (!state.id) return state.text;
    var img = state.element.getAttribute('data-img-src');
    return $(`<span><img src="${img}" class="flag" /> ${state.id} - ${state.text}</span>`);
}


        function convertCurrency() {
            let amount = parseFloat($('#amount').val());
            let fromCurrency = $('#from-currency').val();
            let toCurrency = $('#to-currency').val();

            if (isNaN(amount) || !fromCurrency || !toCurrency) {
                $('#result').text("Please enter a valid amount and select both currencies.");
                return;
            }

            const apiUrl = `https://api.exchangerate-api.com/v4/latest/${fromCurrency}`;

            $.getJSON(apiUrl, function(data) {
                if (data && data.rates[toCurrency]) {
                    let conversionRate = data.rates[toCurrency];
                    let convertedAmount = (amount * conversionRate).toFixed(2);
                    $('#result').text(`${amount} ${fromCurrency} = ${convertedAmount} ${toCurrency}`);
                } else {
                    $('#result').text("Error retrieving conversion data. Please check the selected currencies.");
                }
            }).fail(function() {
                $('#result').text("Error retrieving data. Please try again later.");
            });
        }
